name: First Workflow

# Repository Related Workflow Trigger: push, pull_request, create, issues, fork. discussion, watch etc
# Other Triggers:  workflow_dispatch, repository_dispatch, schedule, workflow_call

on:
  push:
    branches: 
     - main 
     - dev-*
    paths-ignore:
     - '.github/abc/*'
  pull_request:
    types: 
      - opened
    branches: 
     - main 
     - dev-*      
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Install Node JS
        uses: actions/setup-node@v3
        with: 
          node-version: 18


  Second-job:
    needs: first-job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Install Node JS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
